# Generated by Django 6.0 on 2026-01-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_customer_name_customer_customer_product_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
