# Generated by Django 6.0 on 2026-01-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
